#############################################################################
# Makefile for building: libpngjpegz.a
# Generated by qmake (3.0) (Qt 5.1.0) on: Thu Jan 16 12:34:32 2014
# Project:  libpngjpegz.pro
# Template: lib
# Command: /home/richard/Qt5.1.0/5.1.0/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile libpngjpegz.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG
CFLAGS        = -pipe -g -O0 -Wall -Wno-type-limits -Wno-unused-parameter -Wno-implicit-function-declaration -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++ -I. -Ipng -Ipng/h -Izlib -Izlib/h -Ijpeg
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/richard/Qt5.1.0/5.1.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .tmp/

####### Files

SOURCES       = png/pngwutil.c \
		png/pngwtran.c \
		png/pngwrite.c \
		png/pngwio.c \
		png/pngtrans.c \
		png/pngset.c \
		png/pngrutil.c \
		png/pngrtran.c \
		png/pngrio.c \
		png/pngread.c \
		png/pngpread.c \
		png/pngmem.c \
		png/pngget.c \
		png/pngerror.c \
		png/png.c \
		zlib/zutil.c \
		zlib/uncompr.c \
		zlib/trees.c \
		zlib/inftrees.c \
		zlib/inflate.c \
		zlib/inffast.c \
		zlib/infback.c \
		zlib/gzwrite.c \
		zlib/gzread.c \
		zlib/gzlib.c \
		zlib/gzclose.c \
		zlib/deflate.c \
		zlib/crc32.c \
		zlib/compress.c \
		zlib/adler32.c \
		jpeg/jcmaster.c \
		jpeg/jcmarker.c \
		jpeg/jcmainct.c \
		jpeg/jcinit.c \
		jpeg/jchuff.c \
		jpeg/jcdctmgr.c \
		jpeg/jccolor.c \
		jpeg/jccoefct.c \
		jpeg/jcarith.c \
		jpeg/jcapistd.c \
		jpeg/jcapimin.c \
		jpeg/jaricom.c \
		jpeg/jmemmgr.c \
		jpeg/jmemansi.c \
		jpeg/jidctint.c \
		jpeg/jidctfst.c \
		jpeg/jidctflt.c \
		jpeg/jfdctint.c \
		jpeg/jfdctfst.c \
		jpeg/jfdctflt.c \
		jpeg/jerror.c \
		jpeg/jdtrans.c \
		jpeg/jdsample.c \
		jpeg/jdpostct.c \
		jpeg/jdmerge.c \
		jpeg/jdmaster.c \
		jpeg/jdmarker.c \
		jpeg/jdmainct.c \
		jpeg/jdinput.c \
		jpeg/jdhuff.c \
		jpeg/jddctmgr.c \
		jpeg/jdcolor.c \
		jpeg/jdcoefct.c \
		jpeg/jdatasrc.c \
		jpeg/jdatadst.c \
		jpeg/jdarith.c \
		jpeg/jdapistd.c \
		jpeg/jdapimin.c \
		jpeg/jctrans.c \
		jpeg/jcsample.c \
		jpeg/jcprepct.c \
		jpeg/jcparam.c \
		jpeg/jcomapi.c \
		jpeg/jutils.c \
		jpeg/jquant2.c \
		jpeg/jquant1.c 
OBJECTS       = .tmp/pngwutil.o \
		.tmp/pngwtran.o \
		.tmp/pngwrite.o \
		.tmp/pngwio.o \
		.tmp/pngtrans.o \
		.tmp/pngset.o \
		.tmp/pngrutil.o \
		.tmp/pngrtran.o \
		.tmp/pngrio.o \
		.tmp/pngread.o \
		.tmp/pngpread.o \
		.tmp/pngmem.o \
		.tmp/pngget.o \
		.tmp/pngerror.o \
		.tmp/png.o \
		.tmp/zutil.o \
		.tmp/uncompr.o \
		.tmp/trees.o \
		.tmp/inftrees.o \
		.tmp/inflate.o \
		.tmp/inffast.o \
		.tmp/infback.o \
		.tmp/gzwrite.o \
		.tmp/gzread.o \
		.tmp/gzlib.o \
		.tmp/gzclose.o \
		.tmp/deflate.o \
		.tmp/crc32.o \
		.tmp/compress.o \
		.tmp/adler32.o \
		.tmp/jcmaster.o \
		.tmp/jcmarker.o \
		.tmp/jcmainct.o \
		.tmp/jcinit.o \
		.tmp/jchuff.o \
		.tmp/jcdctmgr.o \
		.tmp/jccolor.o \
		.tmp/jccoefct.o \
		.tmp/jcarith.o \
		.tmp/jcapistd.o \
		.tmp/jcapimin.o \
		.tmp/jaricom.o \
		.tmp/jmemmgr.o \
		.tmp/jmemansi.o \
		.tmp/jidctint.o \
		.tmp/jidctfst.o \
		.tmp/jidctflt.o \
		.tmp/jfdctint.o \
		.tmp/jfdctfst.o \
		.tmp/jfdctflt.o \
		.tmp/jerror.o \
		.tmp/jdtrans.o \
		.tmp/jdsample.o \
		.tmp/jdpostct.o \
		.tmp/jdmerge.o \
		.tmp/jdmaster.o \
		.tmp/jdmarker.o \
		.tmp/jdmainct.o \
		.tmp/jdinput.o \
		.tmp/jdhuff.o \
		.tmp/jddctmgr.o \
		.tmp/jdcolor.o \
		.tmp/jdcoefct.o \
		.tmp/jdatasrc.o \
		.tmp/jdatadst.o \
		.tmp/jdarith.o \
		.tmp/jdapistd.o \
		.tmp/jdapimin.o \
		.tmp/jctrans.o \
		.tmp/jcsample.o \
		.tmp/jcprepct.o \
		.tmp/jcparam.o \
		.tmp/jcomapi.o \
		.tmp/jutils.o \
		.tmp/jquant2.o \
		.tmp/jquant1.o
DIST          = ../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		libpngjpegz.pro \
		libpngjpegz.pro
QMAKE_TARGET  = pngjpegz
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libpngjpegz.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) 

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)


Makefile: libpngjpegz.pro ../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		libpngjpegz.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile libpngjpegz.pro
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf:
libpngjpegz.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile libpngjpegz.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/pngjpegz1.0.0 || mkdir -p .tmp/pngjpegz1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pngjpegz1.0.0/ && (cd `dirname .tmp/pngjpegz1.0.0` && $(TAR) pngjpegz1.0.0.tar pngjpegz1.0.0 && $(COMPRESS) pngjpegz1.0.0.tar) && $(MOVE) `dirname .tmp/pngjpegz1.0.0`/pngjpegz1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pngjpegz1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

.tmp/pngwutil.o: png/pngwutil.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngwutil.o png/pngwutil.c

.tmp/pngwtran.o: png/pngwtran.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngwtran.o png/pngwtran.c

.tmp/pngwrite.o: png/pngwrite.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngwrite.o png/pngwrite.c

.tmp/pngwio.o: png/pngwio.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngwio.o png/pngwio.c

.tmp/pngtrans.o: png/pngtrans.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngtrans.o png/pngtrans.c

.tmp/pngset.o: png/pngset.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngset.o png/pngset.c

.tmp/pngrutil.o: png/pngrutil.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngrutil.o png/pngrutil.c

.tmp/pngrtran.o: png/pngrtran.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngrtran.o png/pngrtran.c

.tmp/pngrio.o: png/pngrio.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngrio.o png/pngrio.c

.tmp/pngread.o: png/pngread.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngread.o png/pngread.c

.tmp/pngpread.o: png/pngpread.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngpread.o png/pngpread.c

.tmp/pngmem.o: png/pngmem.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngmem.o png/pngmem.c

.tmp/pngget.o: png/pngget.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngget.o png/pngget.c

.tmp/pngerror.o: png/pngerror.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/pngerror.o png/pngerror.c

.tmp/png.o: png/png.c png/pngpriv.h \
		png/h/png.h \
		png/h/pnglibconf.h \
		png/h/pngconf.h \
		png/pnginfo.h \
		png/pngstruct.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		png/pngdebug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/png.o png/png.c

.tmp/zutil.o: zlib/zutil.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/gzguts.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/zutil.o zlib/zutil.c

.tmp/uncompr.o: zlib/uncompr.c zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/uncompr.o zlib/uncompr.c

.tmp/trees.o: zlib/trees.c zlib/deflate.h \
		zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/trees.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/trees.o zlib/trees.c

.tmp/inftrees.o: zlib/inftrees.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/inftrees.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/inftrees.o zlib/inftrees.c

.tmp/inflate.o: zlib/inflate.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/inftrees.h \
		zlib/inflate.h \
		zlib/inffast.h \
		zlib/inffixed.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/inflate.o zlib/inflate.c

.tmp/inffast.o: zlib/inffast.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/inftrees.h \
		zlib/inflate.h \
		zlib/inffast.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/inffast.o zlib/inffast.c

.tmp/infback.o: zlib/infback.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/inftrees.h \
		zlib/inflate.h \
		zlib/inffast.h \
		zlib/inffixed.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/infback.o zlib/infback.c

.tmp/gzwrite.o: zlib/gzwrite.c zlib/gzguts.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/gzwrite.o zlib/gzwrite.c

.tmp/gzread.o: zlib/gzread.c zlib/gzguts.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/gzread.o zlib/gzread.c

.tmp/gzlib.o: zlib/gzlib.c zlib/gzguts.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/gzlib.o zlib/gzlib.c

.tmp/gzclose.o: zlib/gzclose.c zlib/gzguts.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/gzclose.o zlib/gzclose.c

.tmp/deflate.o: zlib/deflate.c zlib/deflate.h \
		zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/deflate.o zlib/deflate.c

.tmp/crc32.o: zlib/crc32.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h \
		zlib/crc32.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/crc32.o zlib/crc32.c

.tmp/compress.o: zlib/compress.c zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/compress.o zlib/compress.c

.tmp/adler32.o: zlib/adler32.c zlib/zutil.h \
		zlib/h/zlib.h \
		zlib/h/zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/adler32.o zlib/adler32.c

.tmp/jcmaster.o: jpeg/jcmaster.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcmaster.o jpeg/jcmaster.c

.tmp/jcmarker.o: jpeg/jcmarker.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcmarker.o jpeg/jcmarker.c

.tmp/jcmainct.o: jpeg/jcmainct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcmainct.o jpeg/jcmainct.c

.tmp/jcinit.o: jpeg/jcinit.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcinit.o jpeg/jcinit.c

.tmp/jchuff.o: jpeg/jchuff.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jchuff.o jpeg/jchuff.c

.tmp/jcdctmgr.o: jpeg/jcdctmgr.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcdctmgr.o jpeg/jcdctmgr.c

.tmp/jccolor.o: jpeg/jccolor.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jccolor.o jpeg/jccolor.c

.tmp/jccoefct.o: jpeg/jccoefct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jccoefct.o jpeg/jccoefct.c

.tmp/jcarith.o: jpeg/jcarith.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcarith.o jpeg/jcarith.c

.tmp/jcapistd.o: jpeg/jcapistd.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcapistd.o jpeg/jcapistd.c

.tmp/jcapimin.o: jpeg/jcapimin.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcapimin.o jpeg/jcapimin.c

.tmp/jaricom.o: jpeg/jaricom.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jaricom.o jpeg/jaricom.c

.tmp/jmemmgr.o: jpeg/jmemmgr.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jmemsys.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jmemmgr.o jpeg/jmemmgr.c

.tmp/jmemansi.o: jpeg/jmemansi.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jmemsys.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jmemansi.o jpeg/jmemansi.c

.tmp/jidctint.o: jpeg/jidctint.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jidctint.o jpeg/jidctint.c

.tmp/jidctfst.o: jpeg/jidctfst.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jidctfst.o jpeg/jidctfst.c

.tmp/jidctflt.o: jpeg/jidctflt.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jidctflt.o jpeg/jidctflt.c

.tmp/jfdctint.o: jpeg/jfdctint.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jfdctint.o jpeg/jfdctint.c

.tmp/jfdctfst.o: jpeg/jfdctfst.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jfdctfst.o jpeg/jfdctfst.c

.tmp/jfdctflt.o: jpeg/jfdctflt.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jfdctflt.o jpeg/jfdctflt.c

.tmp/jerror.o: jpeg/jerror.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jversion.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jerror.o jpeg/jerror.c

.tmp/jdtrans.o: jpeg/jdtrans.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdtrans.o jpeg/jdtrans.c

.tmp/jdsample.o: jpeg/jdsample.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdsample.o jpeg/jdsample.c

.tmp/jdpostct.o: jpeg/jdpostct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdpostct.o jpeg/jdpostct.c

.tmp/jdmerge.o: jpeg/jdmerge.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdmerge.o jpeg/jdmerge.c

.tmp/jdmaster.o: jpeg/jdmaster.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdmaster.o jpeg/jdmaster.c

.tmp/jdmarker.o: jpeg/jdmarker.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdmarker.o jpeg/jdmarker.c

.tmp/jdmainct.o: jpeg/jdmainct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdmainct.o jpeg/jdmainct.c

.tmp/jdinput.o: jpeg/jdinput.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdinput.o jpeg/jdinput.c

.tmp/jdhuff.o: jpeg/jdhuff.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdhuff.o jpeg/jdhuff.c

.tmp/jddctmgr.o: jpeg/jddctmgr.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h \
		jpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jddctmgr.o jpeg/jddctmgr.c

.tmp/jdcolor.o: jpeg/jdcolor.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdcolor.o jpeg/jdcolor.c

.tmp/jdcoefct.o: jpeg/jdcoefct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdcoefct.o jpeg/jdcoefct.c

.tmp/jdatasrc.o: jpeg/jdatasrc.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdatasrc.o jpeg/jdatasrc.c

.tmp/jdatadst.o: jpeg/jdatadst.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdatadst.o jpeg/jdatadst.c

.tmp/jdarith.o: jpeg/jdarith.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdarith.o jpeg/jdarith.c

.tmp/jdapistd.o: jpeg/jdapistd.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdapistd.o jpeg/jdapistd.c

.tmp/jdapimin.o: jpeg/jdapimin.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jdapimin.o jpeg/jdapimin.c

.tmp/jctrans.o: jpeg/jctrans.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jctrans.o jpeg/jctrans.c

.tmp/jcsample.o: jpeg/jcsample.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcsample.o jpeg/jcsample.c

.tmp/jcprepct.o: jpeg/jcprepct.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcprepct.o jpeg/jcprepct.c

.tmp/jcparam.o: jpeg/jcparam.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcparam.o jpeg/jcparam.c

.tmp/jcomapi.o: jpeg/jcomapi.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jcomapi.o jpeg/jcomapi.c

.tmp/jutils.o: jpeg/jutils.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jutils.o jpeg/jutils.c

.tmp/jquant2.o: jpeg/jquant2.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jquant2.o jpeg/jquant2.c

.tmp/jquant1.o: jpeg/jquant1.c jpeg/jinclude.h \
		jpeg/jconfig.h \
		jpeg/jpeglib.h \
		jpeg/jmorecfg.h \
		jpeg/jpegint.h \
		jpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .tmp/jquant1.o jpeg/jquant1.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_FILE) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

